import type { Metadata } from "next";
import { Roboto, Bitcount } from "next/font/google";
import "./globals.css";

export const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
});
//bitcount google font import
export const bitcount = Bitcount({
  weight: ["400", "700"],
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={` ${bitcount.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
